server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 139.196.72.191:8848
    gateway:
      routes:
        - id: cloud_authority
          uri: lb://cloudAuthority
          predicates:
            - Path=/user/**

